name: GiftCode
version: ${project.version}
main: dev.chanhne.giftcode.Mainplugin
folia-supported: true
api-version: '1.21'
author: Chanhne
softdepend:
  - Vault
  - Economy

commands:
  gc:
    description: Quản lý mã quà tặng (admin)
    usage: /gc <create|info|delete|reload|enable|disable|list|whitelist|permission>
    permission: giftcode.admin
    permission-message: "§cBạn không có quyền sử dụng lệnh này!"
  code:
    description: Sử dụng mã quà tặng (cho người chơi)
    usage: /code <mã_code>

permissions:
  giftcode.admin:
    description: Cho phép sử dụng lệnh /gc (tạo, xóa, reload, ...)
    default: op
  giftcode.use:
    description: Cho phép sử dụng lệnh /gc (tạo, xóa, reload, ...)
    default: op